[package]
name = "tasks"
version = "0.1.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
# Never publish our internal tasks!
publish = false

[dependencies]
failure = "^0.1"
json = "^0.11"
semver = "^0.9"
toml_edit = "^0.1"
